# Generated by Django 4.0.5 on 2023-02-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_email_alter_patient_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='others',
            new_name='nextkin',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='mname',
        ),
        migrations.AddField(
            model_name='patient',
            name='clinic_no',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
