# Generated by Django 4.0.5 on 2023-02-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_rename_others_patient_nextkin_remove_patient_mname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nextkin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
