# Generated by Django 4.1.1 on 2023-02-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_soapnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soapnote',
            name='patient',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
