# Generated by Django 4.1.1 on 2023-02-19 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_remove_soapnote_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='soapnote',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
